import { access } from 'node:fs/promises';
import type { SQLOutputValue } from 'node:sqlite';
import type { SchemaRecord } from 'elt';
import { AppleNotesStream, notesFields } from './apple-notes-stream.ts';
import {
  type NotesScan,
  number,
  type Row,
  string,
  time,
} from './notes-scan.ts';

const {
  id,
  nullableId,
  text,
  nullableText,
  ordinal,
  nullableNumber,
  nullableTimestamp,
  boolean,
} = notesFields;

const properties = {
  id: {
    ...id,
    description:
      'Notes attachment identifier; used by attachment:<id> links in notes.markdown and by attachments.parentId within this source.',
  },
  noteId: {
    ...id,
    description:
      'Owning note identifier; refers to notes.id within this source. One note can have many attachments.',
  },
  parentId: {
    ...nullableId,
    description:
      'Parent attachment identifier in attachments.id within this source, such as a scan gallery containing pages; NULL for a top-level attachment.',
  },
  type: {
    ...text,
    description:
      'Uniform type identifier recorded by Notes, such as com.apple.notes.table. public.data is emitted when Notes has no type value.',
  },
  title: {
    ...nullableText,
    description:
      'User-supplied attachment title, or the stored title when none is supplied; NULL when neither is recorded.',
  },
  filename: {
    ...nullableText,
    description:
      'Original media filename recorded by Notes; NULL when the attachment has no media filename. A name alone does not prove the file is available.',
  },
  url: {
    ...nullableText,
    description:
      'URL recorded by Notes for this attachment; NULL when absent or the owning note is locked.',
  },
  summary: {
    ...nullableText,
    description:
      'Summary stored by Notes, not generated by this connector; NULL when absent or the owning note is locked.',
  },
  ocrText: {
    ...nullableText,
    description:
      'OCR summary already stored by Notes; NULL when absent or locked. This is separate from text produced by a destination file parser.',
  },
  handwritingText: {
    ...nullableText,
    description:
      'Handwriting summary stored by Notes; NULL when absent or the owning note is locked.',
  },
  imageLabels: {
    ...nullableText,
    description:
      'Image classification summary stored by Notes; NULL when absent or the owning note is locked.',
  },
  transcript: {
    ...nullableText,
    description:
      'Additional indexable text stored by Notes, including audio transcripts when present; NULL when absent or locked.',
  },
  fileSize: {
    ...ordinal,
    description:
      'File size recorded by Notes in bytes; 0 is emitted when no numeric size is recorded and does not prove the file is empty.',
  },
  duration: {
    ...nullableNumber,
    description:
      'Duration value recorded by Notes; NULL when absent or zero. The connector passes through the native value without converting units.',
  },
  width: {
    ...nullableNumber,
    description:
      'Width value recorded by Notes; NULL when absent or zero. The connector passes through the native value without converting units.',
  },
  height: {
    ...nullableNumber,
    description:
      'Height value recorded by Notes; NULL when absent or zero. The connector passes through the native value without converting units.',
  },
  latitude: {
    type: ['number', 'null'],
    minimum: -90,
    maximum: 90,
    description: 'Recorded latitude in degrees; NULL when unavailable.',
  },
  longitude: {
    type: ['number', 'null'],
    minimum: -180,
    maximum: 180,
    description: 'Recorded longitude in degrees; NULL when unavailable.',
  },
  createdAt: {
    ...nullableTimestamp,
    description:
      'Attachment creation time recorded by Notes, converted to a UTC instant; NULL when unavailable.',
  },
  modifiedAt: {
    ...nullableTimestamp,
    description:
      'Attachment modification time recorded by Notes, converted to a UTC instant; NULL when unavailable. File download availability can change independently.',
  },
  availableLocally: {
    ...boolean,
    description:
      'Whether the original media file is accessible on this Mac and the owning note is unlocked. False also covers tables and links without a file; it does not imply deletion. Tables are rendered in notes.markdown.',
  },
} as const;

type Attachment = SchemaRecord<typeof properties>;

export class AttachmentsStream extends AppleNotesStream<
  typeof properties,
  Row
> {
  readonly name = 'attachments';
  readonly jsonSchema = {
    type: 'object',
    description:
      'One source record per attachment of an exported note, including files, links, tables and child scan pages. Metadata can exist without a readable file. Locked notes hide attachment content; undownloaded files remain unavailable until Notes downloads them. Relationships name source streams, not destination tables.',
    properties,
    required: Object.keys(properties),
  } as const;
  readonly supportsFileTransfer = true;

  protected rows(scan: NotesScan): readonly Row[] {
    return [...scan.attachments.values()];
  }

  protected async record(row: Row, scan: NotesScan): Promise<Attachment> {
    // A locked note's attachments keep only what the list of attachments
    // shows, not what they contain.
    const content = (value: SQLOutputValue | undefined) =>
      row.locked === 1 ? null : string(value);
    const file = scan.file(row);
    return {
      id: row.ZIDENTIFIER as string,
      noteId: row.note as string,
      parentId: string(row.parent),
      type: string(row.ZTYPEUTI) ?? 'public.data',
      title: string(row.title),
      filename: string(row.ZFILENAME),
      url: content(row.ZURLSTRING),
      summary: content(row.ZSUMMARY),
      ocrText: content(row.ZOCRSUMMARY),
      handwritingText: content(row.ZHANDWRITINGSUMMARY),
      imageLabels: content(row.ZIMAGECLASSIFICATIONSUMMARY),
      transcript: content(row.ZADDITIONALINDEXABLETEXT),
      fileSize: number(row.ZFILESIZE) ?? 0,
      duration: number(row.ZDURATION) || null,
      width: number(row.ZSIZEWIDTH) || null,
      height: number(row.ZSIZEHEIGHT) || null,
      latitude: number(row.ZLATITUDE),
      longitude: number(row.ZLONGITUDE),
      createdAt: time(row.ZCREATIONDATE),
      modifiedAt: time(row.ZMODIFICATIONDATE),
      availableLocally:
        file !== null &&
        (await access(file).then(
          () => true,
          () => false,
        )),
    };
  }

  // The original file, not a staged copy: readers only read it.
  override file(record: Attachment, scan: NotesScan): string | null {
    const row = scan.attachments.get(record.id);
    return record.availableLocally && row !== undefined ? scan.file(row) : null;
  }
}
