import { isDeepStrictEqual } from 'node:util';
import type { Stream } from 'elt';

// Rendering is shared by whole-stream files and individual-record files.
export class MarkdownDocument {
  static readonly marker =
    '<!-- Generated by mac-elt MarkdownDestination v3. -->\n';
  readonly title?: string;

  constructor({ title }: { title?: string } = {}) {
    if (title !== undefined && (!title || title.includes('\0')))
      throw new TypeError('Invalid Markdown title field');
    this.title = title;
    Object.freeze(this);
  }

  // A whole-stream document carries its writer; a per-record document does not.
  header(stream: Stream, writer?: string): string {
    const owner =
      writer === undefined
        ? ''
        : `<!-- mac-elt-writer:${Buffer.from(writer).toString('base64')} -->\n`;
    return `${MarkdownDocument.marker}${owner}# ${this.escape(stream.name.replaceAll(/\s+/g, ' '))}\n\n`;
  }

  static writer(document: string): string {
    const match = /^<!-- mac-elt-writer:([A-Za-z0-9+/=]+) -->$/m.exec(document);
    const encoded = match?.[1];
    if (encoded === undefined) throw new TypeError('Missing Markdown writer');
    const bytes = Buffer.from(encoded, 'base64');
    if (bytes.toString('base64') !== encoded)
      throw new TypeError('Invalid Markdown writer');
    return bytes.toString('utf8');
  }

  render(data: unknown, index: number): string {
    if (data === null || typeof data !== 'object' || Array.isArray(data))
      throw new TypeError('Markdown records must be JSON-compatible objects');
    const json = JSON.stringify(data);
    // Reject silent JSON losses such as undefined fields, NaN, and Date coercion.
    const record: Record<string, unknown> = JSON.parse(json);
    if (!isDeepStrictEqual(data, record))
      throw new TypeError('Markdown records must be JSON-compatible objects');
    let title = `Record ${index}`;
    if (this.title !== undefined) {
      const value = record[this.title];
      if (!Object.hasOwn(record, this.title) || typeof value !== 'string')
        throw new TypeError(
          `Markdown title field "${this.title}" must be text`,
        );
      title = value.replaceAll(/\s+/g, ' ').trim() || title;
    }
    const fields = Object.entries(record).map(
      ([key, value]) =>
        `- **${this.escape(JSON.stringify(key).slice(1, -1))}:** ${this.escape(JSON.stringify(value))}`,
    );
    return `<!-- mac-elt-record:${Buffer.from(json).toString('base64')} -->\n## ${this.escape(title)}\n\n${fields.join('\n')}\n\n`;
  }

  // Records are stored losslessly alongside their rendered Markdown sections.
  static records(document: string): unknown[] {
    const rows = [
      ...document.matchAll(/^<!-- mac-elt-record:([A-Za-z0-9+/=]+) -->$/gm),
    ];
    if (rows.length !== [...document.matchAll(/^## /gm)].length)
      throw new TypeError('Invalid Markdown record metadata');
    return rows.map((match) => {
      const encoded = match[1];
      if (encoded === undefined)
        throw new TypeError('Missing Markdown record metadata');
      const bytes = Buffer.from(encoded, 'base64');
      if (bytes.toString('base64') !== encoded)
        throw new TypeError('Invalid Markdown record metadata');
      return JSON.parse(bytes.toString('utf8'));
    });
  }

  private escape(text: string): string {
    return text.replaceAll(/[!"#$%&'()*+,\-./:;<=>?@[\\\]^_`{|}~]/g, '\\$&');
  }
}
